# 配置服务端口号
server:
  port: 10200

# 配置数据库的连接信息
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spzx-cloud-order?characterEncoding=UTF8
    username: root
    password: Zxc.12345
  cloud:
    openfeign:
      client:
        config:
          default:    #指定服务的日志格式
            logger-level: full
            read-timeout: 5000
            connect-timeout: 2000
#            retryer:  com.peng.order.feign.MyFeignRetryer
    # 配置nacos注册中心的地址
    nacos:
      discovery:
        server-addr: 192.168.6.100:8848
        cluster-name: SH
#        namespace: be346669-02f6-4045-81f5-55b66e91a203
    loadbalancer:
      nacos:
        enabled: true

  application:
    name: cloud-order   # 每一个服务注册到nacos注册中心都需要提供一个服务名称,order微服务注册的时候需要更改微服务名称


# 配置mybatis的相关信息
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.peng.order.entity
  mapper-locations: classpath:/mapper/*.xml


  # 指定某个包的日志级别为debug
logging:
  level:
    com.peng.order.feign: debug